INSERT INTO public.product (p_id, p_name) VALUES (1, 'נעלי ילדים Comfort Sole 35');
INSERT INTO public.product (p_id, p_name) VALUES (2, 'נעלי ספורט Urban Walk 54');
INSERT INTO public.product (p_id, p_name) VALUES (3, 'מגפי עור Urban Walk 22');
INSERT INTO public.product (p_id, p_name) VALUES (4, 'מוקסינים Elite Shoes 69');
INSERT INTO public.product (p_id, p_name) VALUES (5, 'מגפי עור Urban Walk 99');
INSERT INTO public.product (p_id, p_name) VALUES (6, 'סנדלי ערב Elite Shoes 44');
INSERT INTO public.product (p_id, p_name) VALUES (7, 'סנדלי ערב Elite Shoes 66');
INSERT INTO public.product (p_id, p_name) VALUES (8, 'מוקסינים Premium Step 37');
INSERT INTO public.product (p_id, p_name) VALUES (9, 'מוקסינים Elite Shoes 41');
INSERT INTO public.product (p_id, p_name) VALUES (10, 'מוקסינים Urban Walk 51');
INSERT INTO public.product (p_id, p_name) VALUES (11, 'נעלי עקב Urban Walk 64');
INSERT INTO public.product (p_id, p_name) VALUES (12, 'מוקסינים Comfort Sole 59');
INSERT INTO public.product (p_id, p_name) VALUES (13, 'סניקרס Comfort Sole 67');
INSERT INTO public.product (p_id, p_name) VALUES (14, 'נעלי ספורט Premium Step 40');
INSERT INTO public.product (p_id, p_name) VALUES (15, 'נעלי עקב Comfort Sole 19');
INSERT INTO public.product (p_id, p_name) VALUES (16, 'סניקרס Premium Step 72');
INSERT INTO public.product (p_id, p_name) VALUES (17, 'נעלי עקב Comfort Sole 20');
INSERT INTO public.product (p_id, p_name) VALUES (18, 'נעלי עקב Premium Step 78');
INSERT INTO public.product (p_id, p_name) VALUES (19, 'סניקרס Premium Step 56');
INSERT INTO public.product (p_id, p_name) VALUES (20, 'מוקסינים Premium Step 57');
INSERT INTO public.product (p_id, p_name) VALUES (21, 'נעלי ספורט Premium Step 79');
INSERT INTO public.product (p_id, p_name) VALUES (22, 'נעלי ספורט Premium Step 91');
INSERT INTO public.product (p_id, p_name) VALUES (23, 'נעלי עקב Urban Walk 39');
INSERT INTO public.product (p_id, p_name) VALUES (24, 'נעלי ספורט Elite Shoes 12');
INSERT INTO public.product (p_id, p_name) VALUES (25, 'סנדלי ערב Premium Step 95');
INSERT INTO public.product (p_id, p_name) VALUES (26, 'מוקסינים Premium Step 17');
INSERT INTO public.product (p_id, p_name) VALUES (27, 'נעלי עקב Urban Walk 49');
INSERT INTO public.product (p_id, p_name) VALUES (28, 'נעלי עקב Elite Shoes 11');
INSERT INTO public.product (p_id, p_name) VALUES (29, 'מגפי עור Elite Shoes 49');
INSERT INTO public.product (p_id, p_name) VALUES (30, 'נעלי ספורט Elite Shoes 96');
INSERT INTO public.product (p_id, p_name) VALUES (31, 'סניקרס Elite Shoes 70');
INSERT INTO public.product (p_id, p_name) VALUES (32, 'מוקסינים Elite Shoes 87');
INSERT INTO public.product (p_id, p_name) VALUES (33, 'מוקסינים Elite Shoes 80');
INSERT INTO public.product (p_id, p_name) VALUES (34, 'נעלי עקב Premium Step 56');
INSERT INTO public.product (p_id, p_name) VALUES (35, 'נעלי ילדים Urban Walk 90');
INSERT INTO public.product (p_id, p_name) VALUES (36, 'סניקרס Comfort Sole 73');
INSERT INTO public.product (p_id, p_name) VALUES (37, 'נעלי עקב Premium Step 59');
INSERT INTO public.product (p_id, p_name) VALUES (38, 'סניקרס Premium Step 91');
INSERT INTO public.product (p_id, p_name) VALUES (39, 'מגפי עור Comfort Sole 28');
INSERT INTO public.product (p_id, p_name) VALUES (40, 'סניקרס Elite Shoes 24');
INSERT INTO public.product (p_id, p_name) VALUES (41, 'מוקסינים Comfort Sole 14');
INSERT INTO public.product (p_id, p_name) VALUES (42, 'נעלי עקב Comfort Sole 95');
INSERT INTO public.product (p_id, p_name) VALUES (43, 'מוקסינים Elite Shoes 47');
INSERT INTO public.product (p_id, p_name) VALUES (44, 'מגפי עור Urban Walk 33');
INSERT INTO public.product (p_id, p_name) VALUES (45, 'סניקרס Comfort Sole 15');
INSERT INTO public.product (p_id, p_name) VALUES (46, 'נעלי ילדים Elite Shoes 17');
INSERT INTO public.product (p_id, p_name) VALUES (47, 'נעלי עקב Urban Walk 26');
INSERT INTO public.product (p_id, p_name) VALUES (48, 'נעלי עקב Comfort Sole 10');
INSERT INTO public.product (p_id, p_name) VALUES (49, 'מגפי עור Urban Walk 17');
INSERT INTO public.product (p_id, p_name) VALUES (50, 'נעלי ספורט Premium Step 33');
INSERT INTO public.product (p_id, p_name) VALUES (51, 'מוקסינים Elite Shoes 47');
INSERT INTO public.product (p_id, p_name) VALUES (52, 'נעלי ספורט Comfort Sole 38');
INSERT INTO public.product (p_id, p_name) VALUES (53, 'מוקסינים Comfort Sole 73');
INSERT INTO public.product (p_id, p_name) VALUES (54, 'נעלי ספורט Comfort Sole 14');
INSERT INTO public.product (p_id, p_name) VALUES (55, 'נעלי ספורט Urban Walk 67');
INSERT INTO public.product (p_id, p_name) VALUES (56, 'נעלי ספורט Premium Step 26');
INSERT INTO public.product (p_id, p_name) VALUES (57, 'סנדלי ערב Premium Step 15');
INSERT INTO public.product (p_id, p_name) VALUES (58, 'סניקרס Urban Walk 90');
INSERT INTO public.product (p_id, p_name) VALUES (59, 'סניקרס Premium Step 52');
INSERT INTO public.product (p_id, p_name) VALUES (60, 'סנדלי ערב Urban Walk 68');
INSERT INTO public.product (p_id, p_name) VALUES (61, 'מוקסינים Urban Walk 28');
INSERT INTO public.product (p_id, p_name) VALUES (62, 'נעלי עקב Comfort Sole 45');
INSERT INTO public.product (p_id, p_name) VALUES (63, 'סניקרס Comfort Sole 85');
INSERT INTO public.product (p_id, p_name) VALUES (64, 'סניקרס Premium Step 82');
INSERT INTO public.product (p_id, p_name) VALUES (65, 'מגפי עור Comfort Sole 13');
INSERT INTO public.product (p_id, p_name) VALUES (66, 'נעלי ספורט Elite Shoes 45');
INSERT INTO public.product (p_id, p_name) VALUES (67, 'נעלי עקב Urban Walk 69');
INSERT INTO public.product (p_id, p_name) VALUES (68, 'נעלי עקב Comfort Sole 51');
INSERT INTO public.product (p_id, p_name) VALUES (69, 'מוקסינים Urban Walk 86');
INSERT INTO public.product (p_id, p_name) VALUES (70, 'מוקסינים Elite Shoes 36');
INSERT INTO public.product (p_id, p_name) VALUES (71, 'מוקסינים Elite Shoes 34');
INSERT INTO public.product (p_id, p_name) VALUES (72, 'סנדלי ערב Urban Walk 45');
INSERT INTO public.product (p_id, p_name) VALUES (73, 'נעלי ספורט Elite Shoes 72');
INSERT INTO public.product (p_id, p_name) VALUES (74, 'נעלי עקב Comfort Sole 41');
INSERT INTO public.product (p_id, p_name) VALUES (75, 'מגפי עור Premium Step 13');
INSERT INTO public.product (p_id, p_name) VALUES (76, 'סניקרס Premium Step 41');
INSERT INTO public.product (p_id, p_name) VALUES (77, 'מגפי עור Premium Step 88');
INSERT INTO public.product (p_id, p_name) VALUES (78, 'נעלי ספורט Premium Step 95');
INSERT INTO public.product (p_id, p_name) VALUES (79, 'נעלי עקב Elite Shoes 65');
INSERT INTO public.product (p_id, p_name) VALUES (80, 'נעלי ילדים Comfort Sole 16');
INSERT INTO public.product (p_id, p_name) VALUES (81, 'סנדלי ערב Elite Shoes 78');
INSERT INTO public.product (p_id, p_name) VALUES (82, 'סניקרס Elite Shoes 56');
INSERT INTO public.product (p_id, p_name) VALUES (83, 'מוקסינים Comfort Sole 16');
INSERT INTO public.product (p_id, p_name) VALUES (84, 'נעלי עקב Premium Step 14');
INSERT INTO public.product (p_id, p_name) VALUES (85, 'נעלי ילדים Comfort Sole 46');
INSERT INTO public.product (p_id, p_name) VALUES (86, 'מוקסינים Urban Walk 92');
INSERT INTO public.product (p_id, p_name) VALUES (87, 'נעלי ילדים Premium Step 74');
INSERT INTO public.product (p_id, p_name) VALUES (88, 'נעלי ילדים Elite Shoes 89');
INSERT INTO public.product (p_id, p_name) VALUES (89, 'נעלי ילדים Urban Walk 59');
INSERT INTO public.product (p_id, p_name) VALUES (90, 'מוקסינים Comfort Sole 99');
INSERT INTO public.product (p_id, p_name) VALUES (91, 'מגפי עור Elite Shoes 62');
INSERT INTO public.product (p_id, p_name) VALUES (92, 'נעלי עקב Premium Step 63');
INSERT INTO public.product (p_id, p_name) VALUES (93, 'נעלי ילדים Elite Shoes 72');
INSERT INTO public.product (p_id, p_name) VALUES (94, 'נעלי ילדים Comfort Sole 75');
INSERT INTO public.product (p_id, p_name) VALUES (95, 'נעלי עקב Elite Shoes 90');
INSERT INTO public.product (p_id, p_name) VALUES (96, 'סנדלי ערב Comfort Sole 33');
INSERT INTO public.product (p_id, p_name) VALUES (97, 'נעלי עקב Urban Walk 33');
INSERT INTO public.product (p_id, p_name) VALUES (98, 'נעלי עקב Urban Walk 12');
INSERT INTO public.product (p_id, p_name) VALUES (99, 'נעלי ילדים Comfort Sole 17');
INSERT INTO public.product (p_id, p_name) VALUES (100, 'סניקרס Premium Step 15');
INSERT INTO public.product (p_id, p_name) VALUES (101, 'סניקרס Comfort Sole 31');
INSERT INTO public.product (p_id, p_name) VALUES (102, 'סנדלי ערב Urban Walk 50');
INSERT INTO public.product (p_id, p_name) VALUES (103, 'נעלי ספורט Urban Walk 64');
INSERT INTO public.product (p_id, p_name) VALUES (104, 'מגפי עור Urban Walk 17');
INSERT INTO public.product (p_id, p_name) VALUES (105, 'נעלי ילדים Elite Shoes 58');
INSERT INTO public.product (p_id, p_name) VALUES (106, 'סניקרס Comfort Sole 52');
INSERT INTO public.product (p_id, p_name) VALUES (107, 'סניקרס Comfort Sole 34');
INSERT INTO public.product (p_id, p_name) VALUES (108, 'סנדלי ערב Premium Step 70');
INSERT INTO public.product (p_id, p_name) VALUES (109, 'נעלי ילדים Premium Step 95');
INSERT INTO public.product (p_id, p_name) VALUES (110, 'סניקרס Comfort Sole 28');
INSERT INTO public.product (p_id, p_name) VALUES (111, 'סנדלי ערב Urban Walk 61');
INSERT INTO public.product (p_id, p_name) VALUES (112, 'מוקסינים Elite Shoes 87');
INSERT INTO public.product (p_id, p_name) VALUES (113, 'נעלי עקב Premium Step 51');
INSERT INTO public.product (p_id, p_name) VALUES (114, 'מוקסינים Comfort Sole 10');
INSERT INTO public.product (p_id, p_name) VALUES (115, 'סנדלי ערב Premium Step 97');
INSERT INTO public.product (p_id, p_name) VALUES (116, 'נעלי עקב Urban Walk 39');
INSERT INTO public.product (p_id, p_name) VALUES (117, 'מגפי עור Premium Step 10');
INSERT INTO public.product (p_id, p_name) VALUES (118, 'מוקסינים Comfort Sole 11');
INSERT INTO public.product (p_id, p_name) VALUES (119, 'מגפי עור Premium Step 31');
INSERT INTO public.product (p_id, p_name) VALUES (120, 'מוקסינים Premium Step 63');
INSERT INTO public.product (p_id, p_name) VALUES (121, 'מגפי עור Elite Shoes 59');
INSERT INTO public.product (p_id, p_name) VALUES (122, 'מוקסינים Comfort Sole 28');
INSERT INTO public.product (p_id, p_name) VALUES (123, 'נעלי עקב Urban Walk 36');
INSERT INTO public.product (p_id, p_name) VALUES (124, 'נעלי ילדים Premium Step 63');
INSERT INTO public.product (p_id, p_name) VALUES (125, 'סנדלי ערב Comfort Sole 17');
INSERT INTO public.product (p_id, p_name) VALUES (126, 'מגפי עור Urban Walk 53');
INSERT INTO public.product (p_id, p_name) VALUES (127, 'נעלי ספורט Comfort Sole 31');
INSERT INTO public.product (p_id, p_name) VALUES (128, 'מגפי עור Comfort Sole 50');
INSERT INTO public.product (p_id, p_name) VALUES (129, 'נעלי ספורט Urban Walk 85');
INSERT INTO public.product (p_id, p_name) VALUES (130, 'נעלי ילדים Comfort Sole 97');
INSERT INTO public.product (p_id, p_name) VALUES (131, 'מוקסינים Premium Step 25');
INSERT INTO public.product (p_id, p_name) VALUES (132, 'סניקרס Elite Shoes 10');
INSERT INTO public.product (p_id, p_name) VALUES (133, 'מגפי עור Comfort Sole 96');
INSERT INTO public.product (p_id, p_name) VALUES (134, 'מגפי עור Comfort Sole 51');
INSERT INTO public.product (p_id, p_name) VALUES (135, 'נעלי ספורט Urban Walk 32');
INSERT INTO public.product (p_id, p_name) VALUES (136, 'נעלי עקב Elite Shoes 36');
INSERT INTO public.product (p_id, p_name) VALUES (137, 'נעלי עקב Urban Walk 27');
INSERT INTO public.product (p_id, p_name) VALUES (138, 'סניקרס Comfort Sole 43');
INSERT INTO public.product (p_id, p_name) VALUES (139, 'נעלי עקב Urban Walk 52');
INSERT INTO public.product (p_id, p_name) VALUES (140, 'מגפי עור Premium Step 31');
INSERT INTO public.product (p_id, p_name) VALUES (141, 'נעלי עקב Comfort Sole 27');
INSERT INTO public.product (p_id, p_name) VALUES (142, 'מגפי עור Premium Step 80');
INSERT INTO public.product (p_id, p_name) VALUES (143, 'נעלי ילדים Urban Walk 94');
INSERT INTO public.product (p_id, p_name) VALUES (144, 'נעלי ספורט Comfort Sole 71');
INSERT INTO public.product (p_id, p_name) VALUES (145, 'סניקרס Comfort Sole 91');
INSERT INTO public.product (p_id, p_name) VALUES (146, 'מוקסינים Premium Step 60');
INSERT INTO public.product (p_id, p_name) VALUES (147, 'סנדלי ערב Comfort Sole 32');
INSERT INTO public.product (p_id, p_name) VALUES (148, 'סנדלי ערב Elite Shoes 94');
INSERT INTO public.product (p_id, p_name) VALUES (149, 'נעלי עקב Comfort Sole 10');
INSERT INTO public.product (p_id, p_name) VALUES (150, 'נעלי ילדים Elite Shoes 60');
INSERT INTO public.product (p_id, p_name) VALUES (151, 'נעלי ילדים Comfort Sole 93');
INSERT INTO public.product (p_id, p_name) VALUES (152, 'מגפי עור Elite Shoes 19');
INSERT INTO public.product (p_id, p_name) VALUES (153, 'נעלי ילדים Premium Step 81');
INSERT INTO public.product (p_id, p_name) VALUES (154, 'נעלי ספורט Urban Walk 53');
INSERT INTO public.product (p_id, p_name) VALUES (155, 'מוקסינים Elite Shoes 42');
INSERT INTO public.product (p_id, p_name) VALUES (156, 'סניקרס Premium Step 39');
INSERT INTO public.product (p_id, p_name) VALUES (157, 'נעלי ילדים Elite Shoes 96');
INSERT INTO public.product (p_id, p_name) VALUES (158, 'נעלי ילדים Elite Shoes 48');
INSERT INTO public.product (p_id, p_name) VALUES (159, 'נעלי עקב Premium Step 31');
INSERT INTO public.product (p_id, p_name) VALUES (160, 'נעלי ספורט Comfort Sole 60');
INSERT INTO public.product (p_id, p_name) VALUES (161, 'סנדלי ערב Elite Shoes 89');
INSERT INTO public.product (p_id, p_name) VALUES (162, 'מוקסינים Comfort Sole 99');
INSERT INTO public.product (p_id, p_name) VALUES (163, 'נעלי עקב Comfort Sole 41');
INSERT INTO public.product (p_id, p_name) VALUES (164, 'נעלי ילדים Urban Walk 92');
INSERT INTO public.product (p_id, p_name) VALUES (165, 'מגפי עור Premium Step 10');
INSERT INTO public.product (p_id, p_name) VALUES (166, 'מוקסינים Comfort Sole 69');
INSERT INTO public.product (p_id, p_name) VALUES (167, 'נעלי עקב Urban Walk 31');
INSERT INTO public.product (p_id, p_name) VALUES (168, 'מגפי עור Comfort Sole 20');
INSERT INTO public.product (p_id, p_name) VALUES (169, 'מגפי עור Urban Walk 76');
INSERT INTO public.product (p_id, p_name) VALUES (170, 'נעלי ילדים Elite Shoes 48');
INSERT INTO public.product (p_id, p_name) VALUES (171, 'נעלי ספורט Urban Walk 95');
INSERT INTO public.product (p_id, p_name) VALUES (172, 'סנדלי ערב Urban Walk 76');
INSERT INTO public.product (p_id, p_name) VALUES (173, 'מוקסינים Premium Step 85');
INSERT INTO public.product (p_id, p_name) VALUES (174, 'סנדלי ערב Urban Walk 95');
INSERT INTO public.product (p_id, p_name) VALUES (175, 'נעלי ילדים Comfort Sole 53');
INSERT INTO public.product (p_id, p_name) VALUES (176, 'סניקרס Comfort Sole 38');
INSERT INTO public.product (p_id, p_name) VALUES (177, 'מוקסינים Comfort Sole 77');
INSERT INTO public.product (p_id, p_name) VALUES (178, 'מוקסינים Elite Shoes 53');
INSERT INTO public.product (p_id, p_name) VALUES (179, 'סנדלי ערב Elite Shoes 25');
INSERT INTO public.product (p_id, p_name) VALUES (180, 'סנדלי ערב Urban Walk 89');
INSERT INTO public.product (p_id, p_name) VALUES (181, 'סנדלי ערב Elite Shoes 95');
INSERT INTO public.product (p_id, p_name) VALUES (182, 'סנדלי ערב Elite Shoes 82');
INSERT INTO public.product (p_id, p_name) VALUES (183, 'נעלי ספורט Elite Shoes 36');
INSERT INTO public.product (p_id, p_name) VALUES (184, 'מוקסינים Elite Shoes 11');
INSERT INTO public.product (p_id, p_name) VALUES (185, 'מגפי עור Comfort Sole 61');
INSERT INTO public.product (p_id, p_name) VALUES (186, 'מגפי עור Comfort Sole 34');
INSERT INTO public.product (p_id, p_name) VALUES (187, 'נעלי ספורט Urban Walk 21');
INSERT INTO public.product (p_id, p_name) VALUES (188, 'נעלי ספורט Elite Shoes 97');
INSERT INTO public.product (p_id, p_name) VALUES (189, 'נעלי ילדים Elite Shoes 29');
INSERT INTO public.product (p_id, p_name) VALUES (190, 'סנדלי ערב Comfort Sole 83');
INSERT INTO public.product (p_id, p_name) VALUES (191, 'מוקסינים Elite Shoes 44');
INSERT INTO public.product (p_id, p_name) VALUES (192, 'סנדלי ערב Urban Walk 87');
INSERT INTO public.product (p_id, p_name) VALUES (193, 'נעלי עקב Elite Shoes 68');
INSERT INTO public.product (p_id, p_name) VALUES (194, 'נעלי עקב Elite Shoes 73');
INSERT INTO public.product (p_id, p_name) VALUES (195, 'סניקרס Elite Shoes 21');
INSERT INTO public.product (p_id, p_name) VALUES (196, 'נעלי עקב Premium Step 26');
INSERT INTO public.product (p_id, p_name) VALUES (197, 'נעלי ספורט Elite Shoes 21');
INSERT INTO public.product (p_id, p_name) VALUES (198, 'נעלי ספורט Urban Walk 32');
INSERT INTO public.product (p_id, p_name) VALUES (199, 'נעלי עקב Premium Step 84');
INSERT INTO public.product (p_id, p_name) VALUES (200, 'סנדלי ערב Premium Step 74');
INSERT INTO public.product (p_id, p_name) VALUES (201, 'מוקסינים Elite Shoes 92');
INSERT INTO public.product (p_id, p_name) VALUES (202, 'נעלי עקב Comfort Sole 62');
INSERT INTO public.product (p_id, p_name) VALUES (203, 'מוקסינים Comfort Sole 54');
INSERT INTO public.product (p_id, p_name) VALUES (204, 'סנדלי ערב Urban Walk 49');
INSERT INTO public.product (p_id, p_name) VALUES (205, 'סנדלי ערב Elite Shoes 24');
INSERT INTO public.product (p_id, p_name) VALUES (206, 'סנדלי ערב Urban Walk 11');
INSERT INTO public.product (p_id, p_name) VALUES (207, 'נעלי ילדים Elite Shoes 11');
INSERT INTO public.product (p_id, p_name) VALUES (208, 'נעלי עקב Elite Shoes 92');
INSERT INTO public.product (p_id, p_name) VALUES (209, 'סנדלי ערב Urban Walk 47');
INSERT INTO public.product (p_id, p_name) VALUES (210, 'סנדלי ערב Elite Shoes 64');
INSERT INTO public.product (p_id, p_name) VALUES (211, 'נעלי עקב Comfort Sole 54');
INSERT INTO public.product (p_id, p_name) VALUES (212, 'סניקרס Premium Step 75');
INSERT INTO public.product (p_id, p_name) VALUES (213, 'סנדלי ערב Premium Step 88');
INSERT INTO public.product (p_id, p_name) VALUES (214, 'נעלי ספורט Premium Step 50');
INSERT INTO public.product (p_id, p_name) VALUES (215, 'נעלי ספורט Comfort Sole 36');
INSERT INTO public.product (p_id, p_name) VALUES (216, 'מוקסינים Comfort Sole 20');
INSERT INTO public.product (p_id, p_name) VALUES (217, 'נעלי ילדים Urban Walk 37');
INSERT INTO public.product (p_id, p_name) VALUES (218, 'מוקסינים Comfort Sole 26');
INSERT INTO public.product (p_id, p_name) VALUES (219, 'סנדלי ערב Elite Shoes 68');
INSERT INTO public.product (p_id, p_name) VALUES (220, 'סנדלי ערב Urban Walk 26');
INSERT INTO public.product (p_id, p_name) VALUES (221, 'נעלי ילדים Comfort Sole 38');
INSERT INTO public.product (p_id, p_name) VALUES (222, 'נעלי ילדים Urban Walk 54');
INSERT INTO public.product (p_id, p_name) VALUES (223, 'מגפי עור Premium Step 70');
INSERT INTO public.product (p_id, p_name) VALUES (224, 'נעלי ספורט Premium Step 77');
INSERT INTO public.product (p_id, p_name) VALUES (225, 'סניקרס Elite Shoes 87');
INSERT INTO public.product (p_id, p_name) VALUES (226, 'נעלי עקב Elite Shoes 58');
INSERT INTO public.product (p_id, p_name) VALUES (227, 'נעלי ספורט Comfort Sole 75');
INSERT INTO public.product (p_id, p_name) VALUES (228, 'נעלי ילדים Urban Walk 64');
INSERT INTO public.product (p_id, p_name) VALUES (229, 'מוקסינים Urban Walk 15');
INSERT INTO public.product (p_id, p_name) VALUES (230, 'נעלי ילדים Urban Walk 15');
INSERT INTO public.product (p_id, p_name) VALUES (231, 'מוקסינים Premium Step 52');
INSERT INTO public.product (p_id, p_name) VALUES (232, 'מוקסינים Premium Step 14');
INSERT INTO public.product (p_id, p_name) VALUES (233, 'נעלי ספורט Urban Walk 89');
INSERT INTO public.product (p_id, p_name) VALUES (234, 'סניקרס Premium Step 86');
INSERT INTO public.product (p_id, p_name) VALUES (235, 'נעלי ילדים Elite Shoes 61');
INSERT INTO public.product (p_id, p_name) VALUES (236, 'מוקסינים Urban Walk 51');
INSERT INTO public.product (p_id, p_name) VALUES (237, 'נעלי ספורט Elite Shoes 20');
INSERT INTO public.product (p_id, p_name) VALUES (238, 'מוקסינים Comfort Sole 25');
INSERT INTO public.product (p_id, p_name) VALUES (239, 'נעלי ספורט Premium Step 56');
INSERT INTO public.product (p_id, p_name) VALUES (240, 'מגפי עור Comfort Sole 48');
INSERT INTO public.product (p_id, p_name) VALUES (241, 'נעלי ילדים Urban Walk 41');
INSERT INTO public.product (p_id, p_name) VALUES (242, 'מגפי עור Premium Step 88');
INSERT INTO public.product (p_id, p_name) VALUES (243, 'נעלי עקב Comfort Sole 47');
INSERT INTO public.product (p_id, p_name) VALUES (244, 'סניקרס Elite Shoes 28');
INSERT INTO public.product (p_id, p_name) VALUES (245, 'נעלי ספורט Urban Walk 62');
INSERT INTO public.product (p_id, p_name) VALUES (246, 'סניקרס Urban Walk 88');
INSERT INTO public.product (p_id, p_name) VALUES (247, 'סניקרס Elite Shoes 99');
INSERT INTO public.product (p_id, p_name) VALUES (248, 'מגפי עור Comfort Sole 12');
INSERT INTO public.product (p_id, p_name) VALUES (249, 'מוקסינים Comfort Sole 31');
INSERT INTO public.product (p_id, p_name) VALUES (250, 'סניקרס Premium Step 49');
INSERT INTO public.product (p_id, p_name) VALUES (251, 'נעלי עקב Comfort Sole 22');
INSERT INTO public.product (p_id, p_name) VALUES (252, 'נעלי עקב Premium Step 36');
INSERT INTO public.product (p_id, p_name) VALUES (253, 'מגפי עור Premium Step 76');
INSERT INTO public.product (p_id, p_name) VALUES (254, 'נעלי עקב Elite Shoes 19');
INSERT INTO public.product (p_id, p_name) VALUES (255, 'נעלי ילדים Urban Walk 94');
INSERT INTO public.product (p_id, p_name) VALUES (256, 'נעלי ספורט Elite Shoes 16');
INSERT INTO public.product (p_id, p_name) VALUES (257, 'נעלי ספורט Elite Shoes 69');
INSERT INTO public.product (p_id, p_name) VALUES (258, 'מוקסינים Comfort Sole 22');
INSERT INTO public.product (p_id, p_name) VALUES (259, 'סניקרס Comfort Sole 95');
INSERT INTO public.product (p_id, p_name) VALUES (260, 'מגפי עור Elite Shoes 93');
INSERT INTO public.product (p_id, p_name) VALUES (261, 'סנדלי ערב Premium Step 46');
INSERT INTO public.product (p_id, p_name) VALUES (262, 'נעלי ילדים Comfort Sole 74');
INSERT INTO public.product (p_id, p_name) VALUES (263, 'נעלי עקב Urban Walk 47');
INSERT INTO public.product (p_id, p_name) VALUES (264, 'נעלי ספורט Urban Walk 43');
INSERT INTO public.product (p_id, p_name) VALUES (265, 'נעלי ילדים Comfort Sole 78');
INSERT INTO public.product (p_id, p_name) VALUES (266, 'מוקסינים Premium Step 45');
INSERT INTO public.product (p_id, p_name) VALUES (267, 'סנדלי ערב Premium Step 62');
INSERT INTO public.product (p_id, p_name) VALUES (268, 'נעלי ילדים Comfort Sole 50');
INSERT INTO public.product (p_id, p_name) VALUES (269, 'נעלי ספורט Elite Shoes 47');
INSERT INTO public.product (p_id, p_name) VALUES (270, 'סניקרס Premium Step 33');
INSERT INTO public.product (p_id, p_name) VALUES (271, 'נעלי ילדים Elite Shoes 73');
INSERT INTO public.product (p_id, p_name) VALUES (272, 'נעלי עקב Premium Step 36');
INSERT INTO public.product (p_id, p_name) VALUES (273, 'נעלי עקב Elite Shoes 43');
INSERT INTO public.product (p_id, p_name) VALUES (274, 'סניקרס Premium Step 95');
INSERT INTO public.product (p_id, p_name) VALUES (275, 'נעלי ספורט Comfort Sole 91');
INSERT INTO public.product (p_id, p_name) VALUES (276, 'מגפי עור Urban Walk 72');
INSERT INTO public.product (p_id, p_name) VALUES (277, 'מגפי עור Comfort Sole 78');
INSERT INTO public.product (p_id, p_name) VALUES (278, 'מוקסינים Elite Shoes 47');
INSERT INTO public.product (p_id, p_name) VALUES (279, 'סניקרס Comfort Sole 21');
INSERT INTO public.product (p_id, p_name) VALUES (280, 'מגפי עור Elite Shoes 72');
INSERT INTO public.product (p_id, p_name) VALUES (281, 'מוקסינים Premium Step 25');
INSERT INTO public.product (p_id, p_name) VALUES (282, 'נעלי ספורט Urban Walk 56');
INSERT INTO public.product (p_id, p_name) VALUES (283, 'סנדלי ערב Urban Walk 10');
INSERT INTO public.product (p_id, p_name) VALUES (284, 'מגפי עור Premium Step 43');
INSERT INTO public.product (p_id, p_name) VALUES (285, 'סניקרס Comfort Sole 57');
INSERT INTO public.product (p_id, p_name) VALUES (286, 'נעלי ילדים Urban Walk 27');
INSERT INTO public.product (p_id, p_name) VALUES (287, 'סניקרס Elite Shoes 65');
INSERT INTO public.product (p_id, p_name) VALUES (288, 'סניקרס Urban Walk 85');
INSERT INTO public.product (p_id, p_name) VALUES (289, 'סנדלי ערב Premium Step 94');
INSERT INTO public.product (p_id, p_name) VALUES (290, 'מוקסינים Comfort Sole 75');
INSERT INTO public.product (p_id, p_name) VALUES (291, 'נעלי ילדים Comfort Sole 98');
INSERT INTO public.product (p_id, p_name) VALUES (292, 'מוקסינים Premium Step 90');
INSERT INTO public.product (p_id, p_name) VALUES (293, 'סנדלי ערב Comfort Sole 25');
INSERT INTO public.product (p_id, p_name) VALUES (294, 'נעלי ילדים Comfort Sole 46');
INSERT INTO public.product (p_id, p_name) VALUES (295, 'נעלי ילדים Premium Step 49');
INSERT INTO public.product (p_id, p_name) VALUES (296, 'נעלי ילדים Comfort Sole 95');
INSERT INTO public.product (p_id, p_name) VALUES (297, 'סניקרס Comfort Sole 68');
INSERT INTO public.product (p_id, p_name) VALUES (298, 'נעלי ספורט Comfort Sole 28');
INSERT INTO public.product (p_id, p_name) VALUES (299, 'מוקסינים Urban Walk 73');
INSERT INTO public.product (p_id, p_name) VALUES (300, 'נעלי ילדים Elite Shoes 80');
INSERT INTO public.product (p_id, p_name) VALUES (301, 'נעלי ספורט Comfort Sole 80');
INSERT INTO public.product (p_id, p_name) VALUES (302, 'סנדלי ערב Premium Step 64');
INSERT INTO public.product (p_id, p_name) VALUES (303, 'נעלי ילדים Urban Walk 80');
INSERT INTO public.product (p_id, p_name) VALUES (304, 'מגפי עור Urban Walk 81');
INSERT INTO public.product (p_id, p_name) VALUES (305, 'נעלי ספורט Urban Walk 69');
INSERT INTO public.product (p_id, p_name) VALUES (306, 'נעלי ילדים Urban Walk 61');
INSERT INTO public.product (p_id, p_name) VALUES (307, 'נעלי עקב Urban Walk 68');
INSERT INTO public.product (p_id, p_name) VALUES (308, 'סנדלי ערב Premium Step 78');
INSERT INTO public.product (p_id, p_name) VALUES (309, 'סנדלי ערב Elite Shoes 97');
INSERT INTO public.product (p_id, p_name) VALUES (310, 'נעלי ילדים Elite Shoes 98');
INSERT INTO public.product (p_id, p_name) VALUES (311, 'מוקסינים Comfort Sole 52');
INSERT INTO public.product (p_id, p_name) VALUES (312, 'נעלי ילדים Urban Walk 71');
INSERT INTO public.product (p_id, p_name) VALUES (313, 'נעלי ילדים Urban Walk 11');
INSERT INTO public.product (p_id, p_name) VALUES (314, 'מגפי עור Urban Walk 94');
INSERT INTO public.product (p_id, p_name) VALUES (315, 'מגפי עור Comfort Sole 49');
INSERT INTO public.product (p_id, p_name) VALUES (316, 'נעלי ילדים Urban Walk 91');
INSERT INTO public.product (p_id, p_name) VALUES (317, 'סנדלי ערב Comfort Sole 58');
INSERT INTO public.product (p_id, p_name) VALUES (318, 'נעלי ילדים Premium Step 57');
INSERT INTO public.product (p_id, p_name) VALUES (319, 'מוקסינים Urban Walk 32');
INSERT INTO public.product (p_id, p_name) VALUES (320, 'סנדלי ערב Urban Walk 48');
INSERT INTO public.product (p_id, p_name) VALUES (321, 'מוקסינים Urban Walk 17');
INSERT INTO public.product (p_id, p_name) VALUES (322, 'נעלי עקב Comfort Sole 63');
INSERT INTO public.product (p_id, p_name) VALUES (323, 'נעלי ספורט Elite Shoes 65');
INSERT INTO public.product (p_id, p_name) VALUES (324, 'נעלי ילדים Elite Shoes 60');
INSERT INTO public.product (p_id, p_name) VALUES (325, 'נעלי ילדים Comfort Sole 49');
INSERT INTO public.product (p_id, p_name) VALUES (326, 'נעלי ילדים Comfort Sole 90');
INSERT INTO public.product (p_id, p_name) VALUES (327, 'נעלי עקב Urban Walk 93');
INSERT INTO public.product (p_id, p_name) VALUES (328, 'נעלי עקב Urban Walk 95');
INSERT INTO public.product (p_id, p_name) VALUES (329, 'סנדלי ערב Elite Shoes 46');
INSERT INTO public.product (p_id, p_name) VALUES (330, 'מוקסינים Premium Step 24');
INSERT INTO public.product (p_id, p_name) VALUES (331, 'נעלי ילדים Elite Shoes 10');
INSERT INTO public.product (p_id, p_name) VALUES (332, 'סניקרס Elite Shoes 18');
INSERT INTO public.product (p_id, p_name) VALUES (333, 'נעלי ספורט Urban Walk 28');
INSERT INTO public.product (p_id, p_name) VALUES (334, 'מגפי עור Premium Step 70');
INSERT INTO public.product (p_id, p_name) VALUES (335, 'מוקסינים Elite Shoes 68');
INSERT INTO public.product (p_id, p_name) VALUES (336, 'נעלי ילדים Comfort Sole 16');
INSERT INTO public.product (p_id, p_name) VALUES (337, 'מגפי עור Urban Walk 27');
INSERT INTO public.product (p_id, p_name) VALUES (338, 'מוקסינים Elite Shoes 15');
INSERT INTO public.product (p_id, p_name) VALUES (339, 'מוקסינים Urban Walk 52');
INSERT INTO public.product (p_id, p_name) VALUES (340, 'נעלי ספורט Premium Step 63');
INSERT INTO public.product (p_id, p_name) VALUES (341, 'נעלי ספורט Comfort Sole 36');
INSERT INTO public.product (p_id, p_name) VALUES (342, 'מגפי עור Comfort Sole 11');
INSERT INTO public.product (p_id, p_name) VALUES (343, 'נעלי ספורט Elite Shoes 61');
INSERT INTO public.product (p_id, p_name) VALUES (344, 'סניקרס Premium Step 96');
INSERT INTO public.product (p_id, p_name) VALUES (345, 'סניקרס Premium Step 14');
INSERT INTO public.product (p_id, p_name) VALUES (346, 'סניקרס Elite Shoes 27');
INSERT INTO public.product (p_id, p_name) VALUES (347, 'נעלי ספורט Elite Shoes 72');
INSERT INTO public.product (p_id, p_name) VALUES (348, 'סניקרס Premium Step 64');
INSERT INTO public.product (p_id, p_name) VALUES (349, 'סניקרס Urban Walk 61');
INSERT INTO public.product (p_id, p_name) VALUES (350, 'נעלי עקב Premium Step 51');
INSERT INTO public.product (p_id, p_name) VALUES (351, 'נעלי ספורט Comfort Sole 78');
INSERT INTO public.product (p_id, p_name) VALUES (352, 'סנדלי ערב Urban Walk 92');
INSERT INTO public.product (p_id, p_name) VALUES (353, 'סנדלי ערב Urban Walk 46');
INSERT INTO public.product (p_id, p_name) VALUES (354, 'נעלי ספורט Urban Walk 99');
INSERT INTO public.product (p_id, p_name) VALUES (355, 'נעלי ילדים Urban Walk 26');
INSERT INTO public.product (p_id, p_name) VALUES (356, 'סנדלי ערב Elite Shoes 43');
INSERT INTO public.product (p_id, p_name) VALUES (357, 'נעלי ילדים Premium Step 56');
INSERT INTO public.product (p_id, p_name) VALUES (358, 'נעלי ילדים Comfort Sole 32');
INSERT INTO public.product (p_id, p_name) VALUES (359, 'נעלי ספורט Premium Step 53');
INSERT INTO public.product (p_id, p_name) VALUES (360, 'סנדלי ערב Premium Step 90');
INSERT INTO public.product (p_id, p_name) VALUES (361, 'נעלי ילדים Premium Step 84');
INSERT INTO public.product (p_id, p_name) VALUES (362, 'סניקרס Comfort Sole 72');
INSERT INTO public.product (p_id, p_name) VALUES (363, 'מוקסינים Urban Walk 24');
INSERT INTO public.product (p_id, p_name) VALUES (364, 'סניקרס Comfort Sole 89');
INSERT INTO public.product (p_id, p_name) VALUES (365, 'מוקסינים Urban Walk 61');
INSERT INTO public.product (p_id, p_name) VALUES (366, 'סנדלי ערב Comfort Sole 99');
INSERT INTO public.product (p_id, p_name) VALUES (367, 'סנדלי ערב Urban Walk 44');
INSERT INTO public.product (p_id, p_name) VALUES (368, 'סנדלי ערב Elite Shoes 72');
INSERT INTO public.product (p_id, p_name) VALUES (369, 'נעלי עקב Elite Shoes 71');
INSERT INTO public.product (p_id, p_name) VALUES (370, 'מוקסינים Comfort Sole 78');
INSERT INTO public.product (p_id, p_name) VALUES (371, 'מגפי עור Premium Step 22');
INSERT INTO public.product (p_id, p_name) VALUES (372, 'סניקרס Urban Walk 93');
INSERT INTO public.product (p_id, p_name) VALUES (373, 'נעלי ספורט Comfort Sole 12');
INSERT INTO public.product (p_id, p_name) VALUES (374, 'נעלי עקב Elite Shoes 44');
INSERT INTO public.product (p_id, p_name) VALUES (375, 'סניקרס Comfort Sole 69');
INSERT INTO public.product (p_id, p_name) VALUES (376, 'סנדלי ערב Elite Shoes 59');
INSERT INTO public.product (p_id, p_name) VALUES (377, 'נעלי ילדים Premium Step 24');
INSERT INTO public.product (p_id, p_name) VALUES (378, 'מגפי עור Elite Shoes 88');
INSERT INTO public.product (p_id, p_name) VALUES (379, 'נעלי עקב Elite Shoes 75');
INSERT INTO public.product (p_id, p_name) VALUES (380, 'מוקסינים Comfort Sole 67');
INSERT INTO public.product (p_id, p_name) VALUES (381, 'מוקסינים Comfort Sole 73');
INSERT INTO public.product (p_id, p_name) VALUES (382, 'נעלי ילדים Premium Step 72');
INSERT INTO public.product (p_id, p_name) VALUES (383, 'מוקסינים Elite Shoes 67');
INSERT INTO public.product (p_id, p_name) VALUES (384, 'סנדלי ערב Elite Shoes 87');
INSERT INTO public.product (p_id, p_name) VALUES (385, 'סניקרס Premium Step 69');
INSERT INTO public.product (p_id, p_name) VALUES (386, 'נעלי עקב Premium Step 39');
INSERT INTO public.product (p_id, p_name) VALUES (387, 'נעלי ילדים Premium Step 71');
INSERT INTO public.product (p_id, p_name) VALUES (388, 'מוקסינים Premium Step 34');
INSERT INTO public.product (p_id, p_name) VALUES (389, 'סניקרס Urban Walk 80');
INSERT INTO public.product (p_id, p_name) VALUES (390, 'מגפי עור Elite Shoes 29');
INSERT INTO public.product (p_id, p_name) VALUES (391, 'מגפי עור Comfort Sole 69');
INSERT INTO public.product (p_id, p_name) VALUES (392, 'מוקסינים Comfort Sole 62');
INSERT INTO public.product (p_id, p_name) VALUES (393, 'סנדלי ערב Comfort Sole 44');
INSERT INTO public.product (p_id, p_name) VALUES (394, 'סנדלי ערב Comfort Sole 66');
INSERT INTO public.product (p_id, p_name) VALUES (395, 'מגפי עור Urban Walk 28');
INSERT INTO public.product (p_id, p_name) VALUES (396, 'מגפי עור Premium Step 19');
INSERT INTO public.product (p_id, p_name) VALUES (397, 'מגפי עור Urban Walk 97');
INSERT INTO public.product (p_id, p_name) VALUES (398, 'נעלי ספורט Urban Walk 38');
INSERT INTO public.product (p_id, p_name) VALUES (399, 'סניקרס Elite Shoes 85');
INSERT INTO public.product (p_id, p_name) VALUES (400, 'מגפי עור Premium Step 32');
INSERT INTO public.product (p_id, p_name) VALUES (401, 'נעלי עקב Premium Step 79');
INSERT INTO public.product (p_id, p_name) VALUES (402, 'סניקרס Premium Step 13');
INSERT INTO public.product (p_id, p_name) VALUES (403, 'מוקסינים Elite Shoes 96');
INSERT INTO public.product (p_id, p_name) VALUES (404, 'נעלי ילדים Elite Shoes 24');
INSERT INTO public.product (p_id, p_name) VALUES (405, 'מוקסינים Urban Walk 18');
INSERT INTO public.product (p_id, p_name) VALUES (406, 'נעלי ספורט Elite Shoes 16');
INSERT INTO public.product (p_id, p_name) VALUES (407, 'נעלי ילדים Elite Shoes 54');
INSERT INTO public.product (p_id, p_name) VALUES (408, 'נעלי ספורט Elite Shoes 16');
INSERT INTO public.product (p_id, p_name) VALUES (409, 'סנדלי ערב Comfort Sole 44');
INSERT INTO public.product (p_id, p_name) VALUES (410, 'מגפי עור Elite Shoes 49');
INSERT INTO public.product (p_id, p_name) VALUES (411, 'נעלי ספורט Premium Step 74');
INSERT INTO public.product (p_id, p_name) VALUES (412, 'סנדלי ערב Premium Step 56');
INSERT INTO public.product (p_id, p_name) VALUES (413, 'סנדלי ערב Premium Step 27');
INSERT INTO public.product (p_id, p_name) VALUES (414, 'נעלי ילדים Premium Step 22');
INSERT INTO public.product (p_id, p_name) VALUES (415, 'סנדלי ערב Comfort Sole 77');
INSERT INTO public.product (p_id, p_name) VALUES (416, 'סניקרס Premium Step 36');
INSERT INTO public.product (p_id, p_name) VALUES (417, 'מגפי עור Comfort Sole 90');
INSERT INTO public.product (p_id, p_name) VALUES (418, 'מוקסינים Elite Shoes 58');
INSERT INTO public.product (p_id, p_name) VALUES (419, 'מוקסינים Urban Walk 71');
INSERT INTO public.product (p_id, p_name) VALUES (420, 'סנדלי ערב Premium Step 31');
INSERT INTO public.product (p_id, p_name) VALUES (421, 'סנדלי ערב Elite Shoes 22');
INSERT INTO public.product (p_id, p_name) VALUES (422, 'סנדלי ערב Elite Shoes 86');
INSERT INTO public.product (p_id, p_name) VALUES (423, 'סנדלי ערב Premium Step 56');
INSERT INTO public.product (p_id, p_name) VALUES (424, 'מגפי עור Elite Shoes 59');
INSERT INTO public.product (p_id, p_name) VALUES (425, 'סניקרס Urban Walk 60');
INSERT INTO public.product (p_id, p_name) VALUES (426, 'מוקסינים Elite Shoes 83');
INSERT INTO public.product (p_id, p_name) VALUES (427, 'סניקרס Comfort Sole 43');
INSERT INTO public.product (p_id, p_name) VALUES (428, 'נעלי ילדים Premium Step 58');
INSERT INTO public.product (p_id, p_name) VALUES (429, 'מגפי עור Premium Step 49');
INSERT INTO public.product (p_id, p_name) VALUES (430, 'נעלי ילדים Elite Shoes 16');
INSERT INTO public.product (p_id, p_name) VALUES (431, 'נעלי ספורט Premium Step 33');
INSERT INTO public.product (p_id, p_name) VALUES (432, 'מגפי עור Urban Walk 12');
INSERT INTO public.product (p_id, p_name) VALUES (433, 'מגפי עור Premium Step 46');
INSERT INTO public.product (p_id, p_name) VALUES (434, 'נעלי ילדים Urban Walk 47');
INSERT INTO public.product (p_id, p_name) VALUES (435, 'סנדלי ערב Elite Shoes 87');
INSERT INTO public.product (p_id, p_name) VALUES (436, 'נעלי ספורט Urban Walk 45');
INSERT INTO public.product (p_id, p_name) VALUES (437, 'מגפי עור Urban Walk 11');
INSERT INTO public.product (p_id, p_name) VALUES (438, 'מגפי עור Elite Shoes 20');
INSERT INTO public.product (p_id, p_name) VALUES (439, 'נעלי ילדים Premium Step 62');
INSERT INTO public.product (p_id, p_name) VALUES (440, 'מגפי עור Elite Shoes 51');
INSERT INTO public.product (p_id, p_name) VALUES (441, 'נעלי ילדים Elite Shoes 41');
INSERT INTO public.product (p_id, p_name) VALUES (442, 'סנדלי ערב Premium Step 67');
INSERT INTO public.product (p_id, p_name) VALUES (443, 'מוקסינים Premium Step 49');
INSERT INTO public.product (p_id, p_name) VALUES (444, 'מוקסינים Premium Step 24');
INSERT INTO public.product (p_id, p_name) VALUES (445, 'נעלי עקב Premium Step 26');
INSERT INTO public.product (p_id, p_name) VALUES (446, 'סנדלי ערב Urban Walk 79');
INSERT INTO public.product (p_id, p_name) VALUES (447, 'סנדלי ערב Premium Step 70');
INSERT INTO public.product (p_id, p_name) VALUES (448, 'נעלי ילדים Comfort Sole 87');
INSERT INTO public.product (p_id, p_name) VALUES (449, 'מגפי עור Premium Step 18');
INSERT INTO public.product (p_id, p_name) VALUES (450, 'נעלי ספורט Urban Walk 20');
INSERT INTO public.product (p_id, p_name) VALUES (451, 'מגפי עור Urban Walk 89');
INSERT INTO public.product (p_id, p_name) VALUES (452, 'נעלי עקב Premium Step 10');
INSERT INTO public.product (p_id, p_name) VALUES (453, 'סנדלי ערב Comfort Sole 58');
INSERT INTO public.product (p_id, p_name) VALUES (454, 'נעלי עקב Urban Walk 86');
INSERT INTO public.product (p_id, p_name) VALUES (455, 'מגפי עור Elite Shoes 71');
INSERT INTO public.product (p_id, p_name) VALUES (456, 'סנדלי ערב Comfort Sole 55');
INSERT INTO public.product (p_id, p_name) VALUES (457, 'סניקרס Elite Shoes 98');
INSERT INTO public.product (p_id, p_name) VALUES (458, 'מוקסינים Premium Step 76');
INSERT INTO public.product (p_id, p_name) VALUES (459, 'נעלי ילדים Comfort Sole 20');
INSERT INTO public.product (p_id, p_name) VALUES (460, 'נעלי ילדים Comfort Sole 83');
INSERT INTO public.product (p_id, p_name) VALUES (461, 'מוקסינים Premium Step 50');
INSERT INTO public.product (p_id, p_name) VALUES (462, 'נעלי ילדים Comfort Sole 19');
INSERT INTO public.product (p_id, p_name) VALUES (463, 'סניקרס Premium Step 26');
INSERT INTO public.product (p_id, p_name) VALUES (464, 'מוקסינים Elite Shoes 50');
INSERT INTO public.product (p_id, p_name) VALUES (465, 'נעלי ספורט Urban Walk 89');
INSERT INTO public.product (p_id, p_name) VALUES (466, 'מגפי עור Urban Walk 99');
INSERT INTO public.product (p_id, p_name) VALUES (467, 'נעלי עקב Comfort Sole 84');
INSERT INTO public.product (p_id, p_name) VALUES (468, 'סנדלי ערב Urban Walk 69');
INSERT INTO public.product (p_id, p_name) VALUES (469, 'נעלי עקב Urban Walk 53');
INSERT INTO public.product (p_id, p_name) VALUES (470, 'מגפי עור Urban Walk 33');
INSERT INTO public.product (p_id, p_name) VALUES (471, 'סנדלי ערב Urban Walk 41');
INSERT INTO public.product (p_id, p_name) VALUES (472, 'סנדלי ערב Premium Step 47');
INSERT INTO public.product (p_id, p_name) VALUES (473, 'נעלי עקב Premium Step 34');
INSERT INTO public.product (p_id, p_name) VALUES (474, 'סניקרס Premium Step 83');
INSERT INTO public.product (p_id, p_name) VALUES (475, 'נעלי עקב Elite Shoes 55');
INSERT INTO public.product (p_id, p_name) VALUES (476, 'מוקסינים Urban Walk 22');
INSERT INTO public.product (p_id, p_name) VALUES (477, 'סנדלי ערב Comfort Sole 78');
INSERT INTO public.product (p_id, p_name) VALUES (478, 'נעלי ילדים Elite Shoes 67');
INSERT INTO public.product (p_id, p_name) VALUES (479, 'נעלי עקב Premium Step 18');
INSERT INTO public.product (p_id, p_name) VALUES (480, 'סניקרס Comfort Sole 16');
INSERT INTO public.product (p_id, p_name) VALUES (481, 'נעלי ספורט Premium Step 21');
INSERT INTO public.product (p_id, p_name) VALUES (482, 'סנדלי ערב Urban Walk 20');
INSERT INTO public.product (p_id, p_name) VALUES (483, 'סניקרס Urban Walk 33');
INSERT INTO public.product (p_id, p_name) VALUES (484, 'נעלי עקב Premium Step 81');
INSERT INTO public.product (p_id, p_name) VALUES (485, 'מוקסינים Urban Walk 53');
INSERT INTO public.product (p_id, p_name) VALUES (486, 'מגפי עור Urban Walk 40');
INSERT INTO public.product (p_id, p_name) VALUES (487, 'נעלי ילדים Urban Walk 26');
INSERT INTO public.product (p_id, p_name) VALUES (488, 'מוקסינים Urban Walk 89');
INSERT INTO public.product (p_id, p_name) VALUES (489, 'נעלי ספורט Urban Walk 91');
INSERT INTO public.product (p_id, p_name) VALUES (490, 'סניקרס Premium Step 63');
INSERT INTO public.product (p_id, p_name) VALUES (491, 'מגפי עור Premium Step 15');
INSERT INTO public.product (p_id, p_name) VALUES (492, 'סניקרס Urban Walk 95');
INSERT INTO public.product (p_id, p_name) VALUES (493, 'מגפי עור Premium Step 40');
INSERT INTO public.product (p_id, p_name) VALUES (494, 'נעלי ילדים Urban Walk 89');
INSERT INTO public.product (p_id, p_name) VALUES (495, 'מגפי עור Urban Walk 67');
INSERT INTO public.product (p_id, p_name) VALUES (496, 'סניקרס Elite Shoes 15');
INSERT INTO public.product (p_id, p_name) VALUES (497, 'נעלי ספורט Urban Walk 36');
INSERT INTO public.product (p_id, p_name) VALUES (498, 'נעלי ילדים Urban Walk 83');
INSERT INTO public.product (p_id, p_name) VALUES (499, 'נעלי ספורט Comfort Sole 10');
INSERT INTO public.product (p_id, p_name) VALUES (500, 'סנדלי ערב Comfort Sole 70');
